export function catchUnexpectedError(error: unknown) {
  console.error('An unexpected error occurred.')
}
